[build]
  command = "python generate_static_data.py"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"